<?php
/*
 * This file is part of the Rob Frawley application
 *
 * (c) Rob Frawley 2nd <rmf@robfrawley.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Rf\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository,
    Doctrine\ORM\NoResultException;
use Rf\BlogBundle\Entity\Welcome;

/**
 * WelcomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WelcomeRepository extends EntityRepository 
{
    public function findOneForContext($route = null)
    {
        $q = $this
            ->createQueryBuilder('w')
            ->where('w.matcher LIKE :matcher')
            ->setParameter('matcher', $route)
            ->setMaxResults(1)
            ->getQuery()
        ;

        try {
            $w = $q->getSingleResult();
        }
        catch (NoResultException $e) {
            return new Welcome();
        }

        return $w;
    }
}